// 서비스 워커 — 앱 셸과 에셋을 캐시해 오프라인/홈 화면 앱으로 동작 (캐시 이름을 바꾸면 새 버전 배포)
const CACHE = "poko-focus-v202609151809";
const ASSETS = [
 "assets/bg/attic.jpg",
 "assets/bg/camp.jpg",
 "assets/bg/cave.jpg",
 "assets/bg/forest.jpg",
 "assets/bg/garden.jpg",
 "assets/bg/home.jpg",
 "assets/bg/lab.jpg",
 "assets/bg/orchard.jpg",
 "assets/bg/plaza.jpg",
 "assets/bg/pond.jpg",
 "assets/bg/river.jpg",
 "assets/bg/sky.jpg",
 "assets/bg/stage.jpg",
 "assets/characters/bell.png",
 "assets/characters/bottle.png",
 "assets/characters/chest.png",
 "assets/characters/cloud.png",
 "assets/characters/coin.png",
 "assets/characters/fish.png",
 "assets/characters/fruit.png",
 "assets/characters/lilypad.png",
 "assets/characters/moon.png",
 "assets/characters/planet.png",
 "assets/characters/poko_alert.png",
 "assets/characters/poko_boat.png",
 "assets/characters/poko_encourage.png",
 "assets/characters/poko_excited.png",
 "assets/characters/poko_happy.png",
 "assets/characters/poko_jump.png",
 "assets/characters/poko_neutral.png",
 "assets/characters/poko_proud.png",
 "assets/characters/poko_run.png",
 "assets/characters/poko_sad.png",
 "assets/characters/poko_sleepy.png",
 "assets/characters/poko_surprised.png",
 "assets/characters/poko_thinking.png",
 "assets/characters/spiky_king.png",
 "assets/characters/spiky_nogo.png",
 "assets/characters/star_go.png",
 "assets/characters/star_gold.png",
 "assets/characters/tent.png",
 "assets/hats/crown.png",
 "assets/hats/explorer.png",
 "assets/hats/leaf.png",
 "assets/hats/party.png",
 "assets/hats/star.png",
 "assets/hats/wizard.png",
 "assets/icons/apple-touch-icon.png",
 "assets/icons/icon-192.png",
 "assets/icons/icon-512.png",
 "assets/icons/icon-maskable-512.png",
 "assets/keyvisual.jpg",
 "assets/sprites/poko_dance.png",
 "assets/sprites/poko_idle.png",
 "assets/sprites/poko_jump.png",
 "assets/sprites/poko_run.png",
 "assets/sprites/poko_wave.png",
 "assets/sprites/spiky_idle.png",
 "assets/sprites/star_idle.png",
 "assets/stickers/attic.png",
 "assets/stickers/boss.png",
 "assets/stickers/camp.png",
 "assets/stickers/cave.png",
 "assets/stickers/forest.png",
 "assets/stickers/garden.png",
 "assets/stickers/lab.png",
 "assets/stickers/orchard.png",
 "assets/stickers/plaza.png",
 "assets/stickers/pond.png",
 "assets/stickers/river.png",
 "assets/stickers/sky.png",
 "assets/stickers/stage.png",
 "css/style.css",
 "index.html",
 "js/adaptive.js",
 "js/audio.js",
 "js/fx.js",
 "js/main.js",
 "js/music.js",
 "js/sprite.js",
 "js/stagefx.js",
 "js/storage.js",
 "js/tasks/balloons.js",
 "js/tasks/calc.js",
 "js/tasks/cpt.js",
 "js/tasks/flanker.js",
 "js/tasks/gonogo.js",
 "js/tasks/headcount.js",
 "js/tasks/melody.js",
 "js/tasks/nback.js",
 "js/tasks/search.js",
 "js/tasks/stroop.js",
 "js/tasks/switch.js",
 "js/tasks/trail.js",
 "manifest.json"
];
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS.map((a) => new Request(a, { cache: "reload" }))).catch(() => {})).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request).then((res) => {
    const copy = res.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy)); return res;
  }).catch(() => caches.match("index.html"))));
});
